# Generated by Django 6.0.5 on 2026-05-25 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('scope_category', models.CharField(max_length=10)),
                ('raw_quantity', models.CharField(max_length=100)),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_quantity', models.FloatField(default=0.0)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('SUSPICIOUS', 'Suspicious'), ('FAILED', 'Failed'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('validation_notes', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.ingestionjob')),
            ],
        ),
    ]
